"""fg-amp — Agent Messaging Protocol.

Agent-initiated, end-to-end-encrypted sessions between AI agents:
verifiable agent + owner identity, pairwise and group sessions,
persistent resume, code-enforced contact policies, and untrusted relays.
See docs/BLUEPRINT.md for the protocol design.
"""

from .bodies import (
    BodyRegistry,
    BodyType,
    ClaimBody,
    ClaimPedigree,
    McpBody,
    McpBridge,
    PaymentBody,
    PaymentKind,
    PaymentState,
    PaymentTracker,
    ReceiptBody,
    ReceiptStatus,
    RefBody,
    RefKind,
    SpendLedger,
    TaskBody,
    TaskKind,
    TaskState,
    TaskTracker,
    default_registry,
)
from .envelope import Envelope, EnvelopeType
from .errors import (
    AddressError,
    AmpError,
    BodyError,
    BodyValidationError,
    ConfigurationError,
    DecryptionError,
    DelegationError,
    PaymentLifecycleError,
    PolicyRejection,
    ProtocolVersionError,
    ResumeError,
    SequenceError,
    SessionError,
    SessionNotFoundError,
    SessionStateError,
    SignatureError,
    SpendRejectedError,
    TaskLifecycleError,
    TransportError,
    UnknownBodyTypeError,
    WitnessError,
)
from .identity import (
    AgentCard,
    AgentIdentity,
    Delegation,
    DelegationChain,
    KeyRevocation,
    OwnerIdentity,
    ParticipantCard,
    ParticipantIdentity,
    ParticipantKind,
    Revocation,
    RevocationRegistry,
    address_to_did,
    did_document,
    did_to_address,
    resolve,
    signing_key_from_did,
)
from .node import AmpNode
from .node.node import PendingInitiation
from .policy import ContactPolicy, PolicyMode
from .session import (
    FileSessionStore,
    GroupEvent,
    GroupInfo,
    GroupMessage,
    GroupSession,
    InMemorySessionStore,
    Payload,
    ReceivedMessage,
    Session,
    SessionMode,
    SessionRecord,
    SessionState,
    SessionStats,
    SessionStore,
    WitnessedMessage,
    WitnessReceiver,
    WitnessSpec,
)
from .transport import (
    InMemoryTransport,
    RelayState,
    RelaySyncer,
    RelayTransport,
    SqliteRelayState,
    Transport,
    WakeError,
    WakeNotifier,
    WakePolicy,
    WakeReceiver,
    WsRelayTransport,
    create_relay_app,
)
from .version import PACKAGE_VERSION as __version__

__all__ = [
    "signing_key_from_did",
    "resolve",
    "did_to_address",
    "did_document",
    "address_to_did",
    "AddressError",
    "AgentCard",
    "AgentIdentity",
    "AmpError",
    "AmpNode",
    "BodyError",
    "BodyRegistry",
    "BodyType",
    "BodyValidationError",
    "ClaimBody",
    "ClaimPedigree",
    "McpBody",
    "McpBridge",
    "PaymentBody",
    "PaymentKind",
    "PaymentLifecycleError",
    "PaymentState",
    "PaymentTracker",
    "SpendLedger",
    "SpendRejectedError",
    "ReceiptBody",
    "ReceiptStatus",
    "RefBody",
    "RefKind",
    "TaskBody",
    "TaskKind",
    "TaskLifecycleError",
    "TaskState",
    "TaskTracker",
    "UnknownBodyTypeError",
    "default_registry",
    "ConfigurationError",
    "ContactPolicy",
    "DecryptionError",
    "Delegation",
    "DelegationChain",
    "DelegationError",
    "Envelope",
    "EnvelopeType",
    "FileSessionStore",
    "GroupEvent",
    "GroupInfo",
    "GroupMessage",
    "GroupSession",
    "InMemorySessionStore",
    "InMemoryTransport",
    "PendingInitiation",
    "KeyRevocation",
    "OwnerIdentity",
    "ParticipantCard",
    "ParticipantIdentity",
    "ParticipantKind",
    "Payload",
    "PolicyMode",
    "PolicyRejection",
    "ProtocolVersionError",
    "ReceivedMessage",
    "RelayState",
    "RelayTransport",
    "WakeError",
    "WakeNotifier",
    "WakeReceiver",
    "WakePolicy",
    "ResumeError",
    "Revocation",
    "RevocationRegistry",
    "SequenceError",
    "SqliteRelayState",
    "Session",
    "SessionError",
    "SessionMode",
    "SessionNotFoundError",
    "SessionRecord",
    "SessionState",
    "SessionStateError",
    "SessionStats",
    "SessionStore",
    "SignatureError",
    "HttpTransport",
    "Transport",
    "TransportError",
    "WitnessError",
    "WitnessReceiver",
    "WitnessSpec",
    "WitnessedMessage",
    "RelaySyncer",
    "WsRelayTransport",
    "__version__",
    "create_inbox_router",
    "create_relay_app",
]


def __getattr__(name: str):
    # HttpTransport / create_inbox_router need the optional [http] extra.
    if name in ("HttpTransport", "create_inbox_router"):
        from . import transport

        return getattr(transport, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
